PAD_SIZE = 1024

REWRITE_INFLATION_LIMIT = 10
REWRITE_INFLATION_LIMIT_REORDER = 3
REWRITE_INFLATION_LIMIT_DEMORGAN = 4
REWRITE_INFLATION_LIMIT_DISTRIBUTIVE = 8
REWRITE_VALIDATION_EMPTY_PROB = 0.1
REWRITE_VALIDATIN_TEST_LENGTH = 100
REWRITE_VALIDATION_NUM_TESTS = 1000

VALIDATE_EXAMPLES = False
VALIDATE_AUGMENTED = False
assert not VALIDATE_AUGMENTED or VALIDATE_EXAMPLES
